### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by steve-kaufman** [nikvdp/ejs-syntax#1]
Using a custom ejs filetype instead of the html filetype breaks vim's autoindentation. This is a big issue because of how useful vim's "=" command normally is.

**Comment by josephemorgan** [comment]
Damn, was hoping to see a fix for this. Would love to know a workaround if anyone can find it. I rely pretty heavily on gg=G to autoindent my files.

**Comment by nikvdp** [comment]
@josephemorgan91 just merged in @steve-kaufman’s fix for this
